- name: Create app directory
  file:
    path: "{{ minio_app_dir }}"
    state: directory
    owner: "1000"
    group: "1000"
    mode: "0755"

- name: Create data directory
  file:
    path: "{{ minio_data_dir }}"
    state: directory
    owner: "1000"
    group: "1000"
    mode: "0755"

- name: Copy template docker-compose.yml
  template:
    src: docker-compose.yml
    dest: "{{ minio_app_dir }}/docker-compose.yml"
    mode: "0644"

- name: Start MinIO container in Docker
  block:
  - name: Define variables to docker tls if necessary
    import_tasks: define_docker_host.yml

  - name: Check if MinIO container is running
    command: docker ps --filter "name={{ minio_container_name }}" --format "{{'{{.Names}}'}}"
    register: minio_status
    changed_when: false
    failed_when: false

  - name: Stop current MinIO container if running
    when: minio_status.stdout != ""
    command: /usr/bin/docker stop --timeout 7 {{ minio_container_name }}
    args:
      chdir: "{{ minio_app_dir }}"
    ignore_errors: true

  - name: Start MinIO server container
    command: /usr/bin/docker compose up -d
    args:
      chdir: "{{ minio_app_dir }}"

  - name: Wait for MinIO port 9000 to be available
    ansible.builtin.wait_for:
      port: 9000
      timeout: 60

  environment: "{{ docker_env | default({}) }}"
