- name: Create app directory
  file:
    path: "{{ minio_app_dir }}"
    state: directory
    owner: "1000"
    group: "1000"
    mode: "0755"

- name: Create data directory
  file:
    path: "{{ minio_data_dir }}"
    state: directory
    owner: "1000"
    group: "1000"
    mode: "0755"

- name: Copy template docker-compose.yml
  template:
    src: docker-compose.yml
    dest: "{{ minio_app_dir }}/docker-compose.yml"
    mode: "0644"

- name: Check if TLS is enabled in Docker
  stat:
    path: "{{ ansible_env.HOME }}/.docker/cert.pem"
  register: docker_tls_cert

- name: Define variables to docker tls
  set_fact:
    docker_env:
      DOCKER_HOST: tcp://127.0.0.1:2376
      DOCKER_TLS_VERIFY: '1'
      DOCKER_CERT_PATH: "{{ ansible_env.HOME }}/.docker"
  when: docker_tls_cert.stat.exists

- name: Start MinIO container in Docker
  block:
    - name: Check if MinIO container is running
      command: docker ps --filter "name={{ minio_container_name }}" --format "{{'{{.Names}}'}}"
      register: minio_status
      changed_when: false
      failed_when: false

    - name: Stop current MinIO container if running
      when: minio_status.stdout != ""
      command: /usr/bin/docker stop --timeout 7 {{ minio_container_name }}
      args:
        chdir: "{{ minio_app_dir }}"
      ignore_errors: true

    - name: Start MinIO container
      command: /usr/bin/docker compose up -d
      args:
        chdir: "{{ minio_app_dir }}"
  environment: "{{ docker_env | default({}) }}"
