services:
  {{ minio_container_name }}:
    image: {{ minio_image }}
    container_name: {{ minio_container_name }}
    ports:
      - "{{ minio_api_port }}:9000"
      - "{{ minio_console_port }}:9001"
    volumes:
      - "{{ minio_data_dir }}:/data"
    environment:
      MINIO_ROOT_USER: {{ minio_user }}
      MINIO_ROOT_PASSWORD: {{ minio_password }}
    command: server /data --console-address ":9001"
    restart: {{ minion_restart }} 
